---
before_script: script/build travis
script: script/test travis
after_success:
- script/push ci-images
- script/push by-trigger
sudo: 9000
env:
  matrix:
  - DOCKER_REPO=ubuntu
  - DOCKER_REPO=alpine
  global:
  - secure: "\
      gr4VvqhmaRffcoQzJHNbR+z77xiBqH4lRWplYUgWmOjwasEXR5/eNvYRdUuymlBgIadkDVyS\
      pmCb3yP+SuW5mjKM1OmtFmrWkYIvt90gc4O1V5EEGv/XYEJTlw1bYbkqwG3emv/2GgZg4wm7\
      eJJqD/vU7dopZcjZeZEQlFp1fDnii0w8D20WpMnyuLynvma0Hvp6s/pUG8dHDFqeqLZUQAOP\
      N907xwm8icA8g4PmjYbxcImlZLkwf+ENODk65b4uxXBNhoQ0FuLniKSnkgrd/j1ITWBda3MM\
      /60QCvYDbwFGQmhJayi/cPrd+6Fe/udhUGL4RV6smrPff99K7IZGfMIj9eLOkQOGCjI+hAPm\
      ahIP1P7vhJKYkctMUUskUox4/3jm97qBvVCfQXaijYbbRO0bdGqYlWAQ1AwPdkenPVk6Ki3r\
      Th/NsNPHkiUg7g6SuwC++beaIi0YGz0kZuhBiXFZO7/2l23cGq/YAhJNo7W0T8BegeKUors8\
      L+L4iZTNmswcLzYJFTRzqCfOcJPMvmrvfOgr/VbWB5ejaHNj81W9uuqWTfN06SJ4NPi7tbNj\
      8L46A+bwc4VujKwype4a5xuhzczsnBschYe0fuNd4FsameWhUznEw4iaMNxIKa4AbdjHSj51\
      eql50STPtl8QiMT57ZqRXKxps+/obFQjTcI=\
    "
  - secure: "\
      Y/YukPeJtK43vWNz9Lua+jNSqY2OESkqd0aY6wIpxf14tGEaco8S44RJ4UF3ZVDoVD9teDlS\
      V6cXSucfSMp5/iZMpe5bHvr6t8pfm2POCODBq1Fr8c5XqEbNihx58OhiT8ASHEfrNN5z9svH\
      PnrafyeCdm7SO3naw7qjxWqwwH34I3zJwh0RSC9LOniYO4D5nr/66F6Q33vN4hy4N43A1cAC\
      0Z4ZjbLL2AYm0rzRFpjb3w8mLRD8569MTrandtZ7GCILNxlrNcOrFjJWABSYd/PSMwIcuLrK\
      3KiwRUp4t/r4R6EknWYLaowrHznIEE23nrrH95bWdyFd4OdCkVXcwU7b53emvdKISSMou0hj\
      Do31Q2oIvP0keGHK63wDDxIA8LgoP5q49PtHJOs3G2TIwNWEGc7sOWGGykBu1xyhDB03cl1G\
      cmuaQKwtVmMZP8Ks+X0gQ+5LF9EYVmh1xoA2WHTjuf90WU2Hu5Dr2RfqHTyx4dQoLD1KxpjP\
      fHfoV+DadylrTvtV+EoBMEIAlT8mYuy5DuONSmyeyy8l+nk9am6FPTCCziKQtlOxvaowwlNz\
      5jrpaA9QkFjIeIpQjTh2H0YBXPpDENxeE9w1V+/OlqgZFmlsIm23VxiDdoOtZd5+bz3mzWqH\
      Xy9Yx5HAFG0O/k7U/wXYDXbCZ0ayq+wHg2c=\
    "
  - secure: "\
      cNfo+c5/85HLHP/V6DmNNJT5yHc83O5IPeGR7ZJhniE5CErzovSkmQ8Bcen/xPO0SP9Nb1FP\
      mFyhqg2ySCsRs5Zq/wHRosSzE04tE+eCfRmFWLtzg0l8x5bBh2DpGwLGjLWFbc5idqwEo6K3\
      gYdq3SkVp7PW3mYyH/1Xh5ntZjDkcSn6KGMYcX33DeK0gr6Y1G3PadkEsdqFZ4UqHA/8SELz\
      Fecfg+Vx0mYeqUGwiGkB3m6zxcX+TQkJO/RvR6G7wm+TwqGkU3vhR9PNPMIqWJTx/+Ixn6Q7\
      JLTPV7oMg+xb/QJyUf/lp/UfD7f3Lyj/jHhbutSGkRlGJA89x1eEPizMBkYqHXi18s2TgsIN\
      ggJCvrBRfEAYd3m/nDpfscY1qdbhrztI4AE24t5BUqQfFZ188lDOdwGrWyZ+O6Luz0i9mIeL\
      S6zhirRHW5M+xOKdaIy9QV9IAiVXfQA50/qZr2m/9O9b7ap72CRYFwh24FPTj9cjbXLQ0+fw\
      n8trnx1PBhdIN3xhd5J9TItHFxqD6JLd+wFPr31U5m7jS1E+k/BkfTkqiwbDca3OffVBs8cR\
      AcqDtTf6UQcoWApH5jfibK5cNWOFKGylxcWgffz5YMWMdu+0tw/lZdnZgVkimUMouRW1LpaG\
      rUwCVTEtPbakLt0xpJrCsat3599A9A+7f8A=\
    "
  - secure: "\
      VU4JbLLJiC2Ov/ymLMzGh70QYhvAuitE93fmLhJHT0ndZoJcz4vj1uN9hlEGKk8ftcoyneYf\
      r4Z4nx/GXUyd2N+saulXod4KSBbiHJyGiWCpHKosSM6Na+eS84wFXmkf25oFMJk+d2uw90Iv\
      20r1NK2FzOipErVeEorvr8R6fqnxcwGDIHqr2fOW/dtvMIJ0btAlWsThwIuHDV5esjTTZBl/\
      HN8lyv7rAWQ5OGqveN3usdhlEoAL4KtVUJraUgN8SJxx9Snz1nhQpzLruw9d/DT8Bt8Kskob\
      yho/y9Gr0bHFxVmhbEbF7XP1FiH05h9IpoqIZZrdRuwsfIFgqAjFLca7F2iY7hH3y2S5rm4X\
      bfOKRAvC8LwvABQD6TPJxbB09xFJAGdSTletlI7BERhGD8gba7Yz7VwBhFXjQ+hJVEBIzWBJ\
      pnyv/PvnbjxBv1HEKrcS/VlQsSECMtZXe8vZysSqw1nglWxQzrHGZ2PQIeCQum1SerL7jPQa\
      IBLYR9HgfUQIlIIfkfCKuUvJA7XMjd0dOHrLF2VqLKyJv4tedWbNGqmD6G6hDp6NnMlZyYTT\
      lBKZImHud1hArxQ4hLyZldAxU5iKGNEDghbE2vm6zGX0aBwkGm3CyYil+ubfX/ckUSUeUdBR\
      oGWC37cGBFv0DWCqvSVn1gICCXPkfAKqVBk=\
    "
