#!/bin/sh
[ "$DEBUG" ] && set -x
set -e

# --
# @echo Nothing
# Searches for `.apt` and installs.
# @return 0
# --
install_from_apt_file() {
  if [ "$1" = "apt" ] || [ -f ".apt" ]; then
    touch /etc/apt/ran-user-install

    apt-get update
    apt-get install --no-install-recommends -y "$(cat .apt)"
    cleanup
  fi

  return 0
}

# --
# @echo Nothing
# Cleans up Debian with Deborphan.
# @return 0
# --
apt_clean() {
  apt-get install --no-install-recommends --assume-yes deborphan
  until [ -z "$(deborphan --guess-all)" ]; do
    apt-get autoremove --purge -y "$@" $(
      deborphan --guess-all
    )
  done

  # Don't leave our depedencies lying around.
  apt-get autoremove --purge --assume-yes deborphan
  return 0
}
