#!/bin/sh
set -e
chown -R postgres:postgres  /srv/postgresql
if [ -z "$(ls -A /srv/postgresql)" ]; then
  chpst -u postgres initdb -D /srv/postgresql
fi

exec chpst -u postgres postgres -D /srv/postgresql -c \
  'config_file=/etc/postgresql/postgresql.conf'
