#!/bin/sh
set -e
[ "$DEBUG" ] && set -x
ssh-keygen -A

if [ "$USER" = "user" ] || [ "$PASS" = "password" ]; then
  printf "You are running insecurely\n"
  printf "Override USER and PASS\n"
fi

adduser -D $USER || true
echo "$USER:$PASS" | chpasswd
mkdir -p /home/$USER
chown -R $USER:$USER /home/$USER
exec /usr/sbin/sshd \
  "$@"