#!/bin/sh
set -e
[ "$DEBUG" ] && set -x
ssh-keygen -A

if [ "$USER" != "user" ] && [ "$PASSWORD" != "password" ]; then
  adduser -D $USER || true
  echo "$USER:$PASSWORD" | chpasswd
  mkdir -p /home/$USER

  chown -R $USER:$USER \
    /home/$USER
fi

exec /usr/sbin/sshd \
  "$@"
