#!/bin/sh
port=5434
set -e

# --

if [ -f /usr/share/postgresql/default/users ]; then
  echo "/usr/share/postgresql/default/{users,extensions} deprecated"
  echo "Please store them in /etc/postgresql"
  mv /usr/share/postgresql/default/users \
      /etc/postgresql
fi

# --

if [ -f /usr/share/postgresql/default/extensions ]; then
  echo "/usr/share/postgresql/default/{users,extensions} deprecated"
  echo "Please store them in /etc/postgresql"
  mv /usr/share/postgresql/default/extensions \
      /etc/postgresql
fi

# --

if [ "$AUTOMATED_DB_USERS" ]; then
  touch /etc/postgresql/users

  if [ -s /etc/postgresql/users ];
    then echo "Skipping user generation, user already exists"
  else
    username=$(apg -E '^a-z0-9' -n 1 -m 6)
    password=$(apg -n 1 -m 20)

    echo "$username:$password:$username" > \
        /etc/postgresql/users
  fi
fi

# --

if [ -f /etc/postgresql/users ] || [ -f /etc/postgresql/extensions ]; then

  touch /var/log/postgres.tmp.log
  chpst -u postgres postgres -D /srv/postgresql \
    -c "config_file=/etc/postgresql/postgresql.conf" \
    -c "port=$port" 1> /var/log/postgres.tmp.log 2>&1 &
  pid=$!

  count=0; started=
  while [ "$count" -lt 12 ]; do
    count=$(echo "$(($count+1))")
    chpst -u postgres:postgres psql --port=$port -d postgres -c '\l' \
        1> /dev/null 2>&1 && {
      started=true
      break
    }

    sleep 1
  done

  if [ -z "$started" ]; then
    echo "Unable to start Postgresql, maybe this log will help: "
    cat /var/log/postgres.tmp.log
    exit 1
  fi

  if [ -f /usr/share/postgresql/default/users ]; then
    rm -rf /var/log/postgres.tmp.log

    for v in $(cat /usr/share/postgresql/default/users); do
      user=$(echo $v | awk -F: '{ print $1 }')
      pass=$(echo $v | awk -F: '{ print $2 }')
      data=$(echo $v | awk -F: '{ print $3 }')

      if [ "$pass" ]; then
        if ! chpst -u postgres:postgres psql --port=$port -tAc \
            "SELECT 1 FROM pg_roles WHERE rolname='$user'" | grep -q 1;
          then chpst -u postgres:postgres createuser --port=$port \
            --no-superuser --no-createdb --echo $user
        fi

        chpst -u postgres:postgres psql --port=$port -c \
          "ALTER USER $user WITH PASSWORD '$pass';" >/dev/null
      fi

      chpst -u postgres:postgres createdb \
        --port=$port --owner=$user \
          --echo $data || echo "Database already existed, moving along."
    done
  fi

  if [ -f /usr/share/postgresql/default/extensions ]; then
    for v in $(cat /usr/share/postgresql/default/extensions); do
      data=$(echo $v | awk -F: '{ print $1 }')
      exts=$(echo $v | awk -F: '{ print $2 }')
      printf "CREATE EXTENSION %s ON %s\n" "$exts" "$data"
      chpst -u postgres:postgres psql --port=$port -d $data -c \
        "CREATE EXTENSION \"$exts\"" 1> /dev/null
    done
  fi

  rm -rf \
    /var/log/postgres.tmp.log
  kill $pid
  wait $pid
fi

exit 0
