#!/usr/bin/env node

var a = require("/usr/local/lib/ghost/package.json"), fs = require("fs");
if ( "3.1.0" > a.dependencies.sqlite3 ) {
  a.dependencies.sqlite3 = "3.1.0";
  fs.writeFile("/usr/local/lib/ghost/package.json", JSON.stringify(
    a, null, 2
  ));
}

else {
  console.log(
    "It looks like you are already updated."
  );
}
