#!/bin/sh
set -e
for f in /etc/postfix/* /etc/postfix/**/*; do
  if [ -f "$f" ]
  then
    sed -ri "s/__PG_HOSTNAME__/$PG_HOSTNAME/" $f
    sed -ri "s/__PG_PASSWORD__/$PG_PASSWORD/" $f
    sed -ri "s/__PG_USERNAME__/$PG_USERNAME/" $f
    sed -ri "s/__PG_DATABASE__/$PG_DATABASE/" $f
    sed -ri       "s/__HOSTNAME__/$HOSTNAME/" $f
  fi
done

if [ ! -z "$DISABLE_SSL" ]; then
  sed -i '/^smtpd\?\(_use\)\?_tls/s/^\([^#]\)/# \1/g' \
    /etc/postfix/main.cf
fi

# We need to make sure to facilitate chroot, which seems Postfix defaults to.
# Most of this is only slightly adjusted (if at all) from /etc/init.d/postfix

cd "$(postconf -h queue_directory)"
for file in etc/localtime etc/services etc/resolv.conf etc/hosts etc/nsswitch.conf \
    etc/nss_mdns.config; do

  [ -d ${file%/*} ] || mkdir -p ${file%/*}
  [ -f /$file ] && rm -f $file && cp /$file $file
  [ -f  $file ] && chmod a+rX $file
done

(echo /dev/random; echo /dev/urandom) | cpio -pdL --quiet . 2>/dev/null || true
rm -f usr/lib/zoneinfo/localtime
mkdir -p usr/lib/zoneinfo
ln -sf /etc/localtime \
  usr/lib/zoneinfo/localtime

LIBLIST=$(for name in gcc_s nss resolv; do
  for f in /lib/*/lib$name*.so* /lib/lib$name*.so*; do
    if [ -f "$f" ]
      then echo ${f#/}
    fi
  done;
done)

if [ -n "$LIBLIST" ]; then
  for f in $LIBLIST; do
    rm -f $f
  done

  tar cf - -C / $LIBLIST 2>/dev/null | \
    tar xf -
fi

exec chpst \
  /usr/lib/postfix/master
