#!/bin/sh
set -e
for f in /etc/dovecot/* /etc/dovecot/**/*; do
  if [ -f "$f" ]
  then
    sed -ri "s/__PG_HOSTNAME__/$PG_HOSTNAME/" $f
    sed -ri "s/__PG_PASSWORD__/$PG_PASSWORD/" $f
    sed -ri "s/__PG_USERNAME__/$PG_USERNAME/" $f
    sed -ri "s/__PG_DATABASE__/$PG_DATABASE/" $f
    sed -ri       "s/__HOSTNAME__/$HOSTNAME/" $f
  fi
done

if [ ! -z "$DISABLE_SSL" ]; then
  sed -i 's/^\([^#]\)/# \1/g' /etc/dovecot/conf.d/10-ssl.conf
fi

exec dovecot -F -c \
  /etc/dovecot/dovecot.conf
