#!/bin/sh

# Provides a wrapper for Docker that provides mem, docker-compose (as compose)
# and also wraps around restart making it truly restart for services that tend
# to fail upon restart for some reason.

[ "$DEBUG" ] && set -x
root=$(cd "$(dirname "$(readlink -f $0)")/.."; pwd)
set -e
to=$1

if [ "$1" ]
  then shift
  else /usr/bin/docker --help
fi

case $to in
      mem) exec $root/script/docker-mem "$@";;
  compose) exec $root/script/docker-compose "$@";;
    clean) exec $root/script/docker-clean "$@";;
        *) exec /usr/bin/docker "$to" "$@"
esac
