#!/bin/sh
set -e
in_compose=true; no_file=
root=$(cd "$(dirname "$(readlink -f $0)")/.."; pwd)
compose="$root/vendor/docker/compose"

for v in "$@"; do
  if ! echo "$v" | grep -qE "^\-"; then in_compose=; fi
  if [ "$v" = "-f" ] && [ "$in_compose" ]; then
    no_file=true
  fi
done

if [ -z "$no_file" ] && [ "$DOCKER_RECIPES" ] && [ -f "$DOCKER_RECIPES/compose.yml" ]; then
  file="$DOCKER_RECIPES/compose.yml"
elif [ -z "$no_file" ]; then
  file=
  for file in /etc/docker/compose.yml /srv/docker/compose.yml \
      "$DOCKER_RECIPES/compose.yml" compose.yml; do
    [ -f "$file" ] && break || file=;
  done
fi

if [ -z "$no_file" ] && [ "$file" ]; then
  set -- $file "$@"
  cd $(dirname $file)
  set -- "-f" "$@"
fi

$compose \
  "$@"
