#!/bin/sh

# Pulls down images from hub.docker.com since some images are built on
# Travis-CI and pushed directly to hub.docker.com without us.

[ "$DEBUG" ] && set -x
root=$(cd "$(dirname "$(readlink -f $0)")/.."; pwd)
. $root/vendor/script/helpers
set -e

pull() {
  printf "Pulling the image %s\n" $1
  if [ "$SHOW_DOCKER_OUTPUT" ]
    then docker pull $1
    else docker pull $1 > /dev/null
  fi
}

cd $root
if [ $# -eq 1 ]; then
  parse_repository "$1"
  if [ -d "dockerfiles/$repo" ]; then
    cd "dockerfiles/$repo"
    parse_repository "$1"
    
    if [ -x script/pull ]; then script/pull $tag
    elif [ -f options/tags ] && [ "$tag" ]; then
      if grep -qE "^$tag/" options/tags; then
        pull $current_user/$repo:$tag
      else
        >&2 printf "Unable to find the tag %s\n" "$tag"
        exit 1
      fi

    elif [ -f options/tags ]; then
      for v in $(cat options/tags); do
        pull "$current_user/$repo:$(echo $v | awk -F/ '{
          print $1
        }')"
      done

    elif [ -d tags ] && [ "$tag" ]; then
      if [ -d "tags/$tag" ]; then
        pull "$current_user/$repo:$tag"
      else
        >&2 printf "Unknown tag '%s'" $tag
        exit 1
      fi

    elif [ -d tags ]; then
      for v in tags/*; do
        pull "$current_user/$repo:$(
          basename $v
        )"
      done

    else
      pull "$current_user/$repo:${tag:-latest}"
    fi
  else
    >&2 echo "Unknown repository"
    exit 1
  fi
elif [ $# -gt 1 ]; then
  for v in "$@"; do
    $0 $v
  done
else
  for v in dockerfiles/*; do
    $0 "$(
      basename $v
    )"
  done
fi
