#!/bin/sh

# Pulls down images from hub.docker.com since some images are built on
# Travis-CI and pushed directly to hub.docker.com without us.

[ "$DEBUG" ] && set -x
root=$(cd "$(dirname "$(readlink -f $0)")/.."; pwd)
. $root/vendor/script/helpers
yaml=$root/script/yaml
set -e

pull() {
  printf_green "Pulling the image %s\n" $1
  docker pull $1
  clear_screen \
    $1
}

cd $root
if [ $# -eq 1 ]; then
  parse_repository "$1"
  if [ -d "dockerfiles/$repo" ]; then
    cd "dockerfiles/$repo"; parse_repository "$1"
    if [ -x script/pull ]; then script/pull $tag
    elif [ "$tag" = "latest" ]; then pull $current_user/$repo:$tag
    elif ([ "$tag" ] && [ -f opts.yml ] && $yaml -V tags && $yaml tags -V $tag) || \
         ([ "$tag" ] && [ -d tags ] && [ -d "tags/$tag" ]); then
      pull $current_user/$repo:$tag

    elif [ "$tag" ]; then
      >&2 printf_red "Unable to find the tag '%s'\n" $tag
      exit 1

    elif [ -f opts.yml ] && $yaml -V tags; then
      for v in $($yaml -k tags); do
        pull $current_user/$repo:$v
      done
    else
      tag=${tag:-latest}
      pull $current_user/$repo:$tag
    fi
  else
    >&2 echo_red "Unknown repository"
    exit 1
  fi
elif [ $# -gt 1 ]; then
  for v in "$@"; do
    $0 $v
  done
else
  for v in dockerfiles/*; do
    $0 "$(basename $v)"
  done
fi
