#!/bin/sh

root=$(cd "$(dirname "$(readlink -f $0)")/.."; pwd)
folder="$root/dockerfiles/$1"
script="$folder/script/$2"
shift
shift

if [ -d "$folder" ] && [ -x "$script" ]; then
  cd $folder && exec $script \
    "$@"
else
  # You should know your scripts better.
  >&2 printf "Unknown script '%s' in '%s'\n" $script $folder
  exit 1
fi
