#!/bin/sh
set -e

for v in $(cat users.txt); do
  if echo $v | grep -qE "(^\*:|:skip$)"; then
    continue
  else
    usr=$(echo $v | awk -F: '{ print $1 }')
    uid=$(echo $v | awk -F: '{ print $2 }')

    ! getent passwd docker-$usr > /dev/null && {
      sudo groupadd -rg $uid docker-$usr
      sudo useradd   -u $uid -g $uid \
        -rMd /srv/docker/home/$usr docker-$usr
    }
  fi
done
