#!/bin/sh

# Provides an interface to testing Ubuntu and Alpine latest images which
# feature and hold the docker-helpers stuff.  The reason we only test on those
# images (even if others have it) is because we are are only testing
# the helpers and not the images themselves (for now.)

[ "$DEBUG" ] && set -x
root=$(cd "$(dirname "$(readlink -f $0)")/.."; pwd)
. $root/vendor/script/helpers
set -e

if [ $# -eq 1 ] && [ "$1" = "travis" ]; then
  $0 $DOCKER_REPO
  
elif [ $# -eq 1 ] && [ -d "dockerfiles/$1" ]; then
  cd "dockerfiles/$1"
  if [ -x script/test ]; then
    printf "Testing %s" $1
    script/test
  else
    >&2 printf "This image is not testable."
    exit 1
  fi
elif [ $# -gt 1 ]; then
  for v in "$@"; do
    $0 "$v"
  done
else
  for v in dockerfiles/*; do
    if [ -x $v/script/test ]; then
      $0 "$(
        basename $v
      )"
    fi
  done
fi
