#!/bin/sh

# Provides a Travis-CI (or just CI) compatible interface for running script/
# commands with an environment variable that holds the repo being worked on.
# This suites the need to do things like `script/test` in multiple async runs
# without having to build a complicated Matrix.

root=$(cd "$(dirname "$(readlink -f $0)")/.."; pwd)
DOCKER_TRAVIS_REPO=${DOCKER_TRAVIS_REPO:-alpine}
file="$root/script/$1"
shift

if [ -f $file ] && [ -x $file ]; then
  "$file" "$DOCKER_TRAVIS_REPO" \
    "$@"
else
  >&2 echo "Unknown script."
fi
