#!/usr/bin/env bash
exec 2>&1
set -e

touch /run/minidlna/minidlna.pid && chown minidlna:minidlna /run/minidlna/minidlna.pid
chpst -u minidlna:minidlna minidlnad -f /etc/minidlna.conf \
  -P /run/minidlna/minidlna.pid &

while [[ -f /run/minidlna/minidlna.pid ]]; do
  sleep 1
done
