#!/bin/sh
set -e

chpst opendkim \
  -x /etc/opendkim.conf \
  -p local:/var/spool/postfix/opendkim/milter.sock \
  -P /var/run/opendkim/opendkim.pid \
  -u opendkim -f &
pid=$!

printf "%s \n" $pid > /etc/startup3.d/dkim/supervise/daemon
while [ ! -x /var/spool/postfix/opendkim/milter.sock ]; do
  sleep 1
done

chown opendkim.postfix /var/spool/postfix/opendkim/milter.sock
chmod ug+rw /var/spool/postfix/opendkim/milter.sock
wait $pid
