#!/bin/sh
set -ex
port=5434
if [ -f /usr/share/postgresql/default/users ]; then
  chpst -u postgres postgres -D /srv/postgresql -c "port=$port" 1>/dev/null 2>&1 &
  pid=$!

  count=0; started=
  while [ "$count" -lt 12 ]; do
    count=$(echo "$(($count+1))")
    chpst -u postgres:postgres psql --port=$port -d postgres -c '\l' \
        1>/dev/null 2>&1 && {
      started=true
      break
    }

    sleep 1
  done

  if [ -z "$started" ]; then
    echo "Unable to start Postgresql"
    exit 1
  fi

  if kill -0 $pid; then
    for v in $(cat /usr/share/postgresql/default/users); do
      user=$(echo $v | awk -F: '{ print $1 }')
      pass=$(echo $v | awk -F: '{ print $2 }')
      data=$(echo $v | awk -F: '{ print $3 }')

      if [ "$pass" ]; then
        if ! chpst -u postgres:postgres psql --port=$port -tAc \
            "SELECT 1 FROM pg_roles WHERE rolname='$user'" | grep -q 1;
          then chpst -u postgres:postgres createuser --port=$port \
            --no-superuser --no-createdb --echo $user
        fi

        chpst -u postgres:postgres psql --port=$port -c \
          "ALTER USER $user WITH PASSWORD '$pass';" >/dev/null
      fi

      chpst -u postgres:postgres createdb \
        --port=$port --owner=$user \
          $data || true
    done

    kill $pid
    wait $pid
  else
    echo "Unable to start server, bye."
    exit 1
  fi
fi

exit 0
