#!/bin/sh

sed -ri "s/__HOSTNAME__/$HOSTNAME/" \
  /etc/prosody/prosody.cfg.lua
  
ssl_lines() {
  grep -nE '\s+-{2}\s+enable:ssl$' /etc/prosody/prosody.cfg.lua | awk -F: '{
    print $1
  }'
}

if [ "$ENABLE_SSL" ]; then
  for v in $(ssl_lines); do
    sed -ri "${v}s/(\s*)-{2}\s+/\1/" /etc/prosody/prosody.cfg.lua
    sed -ri "${v}s/\s+-{2}\s+enable:ssl\$//" \
      /etc/prosody/prosody.cfg.lua
  done
else
  while { l=$(ssl_lines | head -n1); test -n "$l"; } do sed -i "${l}d" /etc/prosody/prosody.cfg.lua; done
  for v in $(grep -nE '\s+-{2}\s+disable:ssl$' /etc/prosody/prosody.cfg.lua | awk -F: '{ print $1 }'); do
    sed -ri "${v}s/(\s*)-{2}\s+/\1/" /etc/prosody/prosody.cfg.lua
    sed -ri "${v}s/\s+-{2}\s+disable:ssl\$//" \
      /etc/prosody/prosody.cfg.lua
  done
fi

exec chpst -u prosody:prosody \
  prosody
