#!/bin/sh
set -e

dir=/opt/discourse
for file in /opt/discourse/.plugins/*; do
  if [ -d "$file" ]; then
    name=$(basename $file)
    rm -rf $dir/plugins/$name
    cp -R $file $dir/plugins/$name
  fi
done
