#!/bin/sh

rm -rf tags && mkdir tags
root=$(cd "$(dirname $0)/.."; pwd)
parent_root=$(cd "$(dirname $0)/../../.."; pwd)
yaml=$parent_root/script/yaml

for v in $($yaml -k tags); do
  mkdir -p tags/$v
  cp -R copy/ tags/$v/copy
  cp README.md tags/$v

  erb "tag=$v" "script=$($yaml scripts.$v)" "img=$($yaml images.$v)" \
    Dockerfile > tags/$v/Dockerfile
done
